PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema:  <http://schema.org/>
PREFIX clvapit: <http://dati.gov.it/onto/clvapit#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
    ?URI a ?Descrizione_tipo_struttura ;
         rdfs:label ?Denominazione_struttura ;
         clvapit:hasAddress ?Indirizzo ;
         clvapit:hasCity ?URIComune ;
         clvapit:hasProvince ?Sigla_provincia ;
         clvapit:hasRegion ?Descrizione_Regione .
    ?URIComune clvapit:Identifier ?Codice_Comune ;
         rdfs:label ?Comune ;
         owl:sameAs ?cityDBPedia .
           }
WHERE {

BIND (STR(?Sigla_provincia) AS ?Stringa_provincia)

OPTIONAL {
             SERVICE <http://it.dbpedia.org/sparql> {
                 ?cityDBPedia a <http://dbpedia.org/ontology/PopulatedPlace> ;
                 <http://it.dbpedia.org/property/stato> "ITA"@it ;
                 <http://it.dbpedia.org/property/gradoAmministrativo> 3 ;
                 <http://it.dbpedia.org/property/codiceStatistico> ?Codice_Comune ;
               }
            }
BIND (URI(CONCAT('http://dati.gov.it/dataset/aziende-ospedaliere/', ?Codice_struttura)) AS ?URI)
BIND (URI(CONCAT('http://dati.gov.it/dataset/aziende-ospedaliere/comuni/', ?Codice_Comune)) AS ?URIComune)

}
