PREFIX cis: <http://dati.beniculturali.it/cis#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?URI a cis:CulturalInstituteOrSite;
		rdfs:label ?LUOGO;
		cis:hasSite cis:Site.
	
	?URISite a cis:Site;
		cis:HasAddress cis:Address;
		cis:HasGeometry cis:Geometry.

	?URIAddress a cis:Address;
		rdfs:label ?INDIRIZZO;
		cis:FullAddress ?Address.
	
	?URIGeometry a cis:Geometry;
		cis:HasLat ?LAT;
		cis:HasLong ?LON;
  }
  FROM <file:19-luoghi-della-cultura.csv>
  WHERE {
    	BIND (URI(CONCAT('http://dati.comune.matera.it/19luoghicultura/', ?LUOGO)) AS ?URI)
	BIND (URI(CONCAT('http://dati.comune.matera.it/19luoghicultura/', ?INDIRIZZO)) AS ?URIAddress)
	BIND (URI(CONCAT('http://dati.comune.matera.it/19luoghicultura/', ?LUOGO, '/geometry')) AS ?URIGeometry)
	BIND (URI(CONCAT(?URIGeometry, ?LAT)) AS ?lat)
	BIND (URI(CONCAT(?URIGeometry, ?LON)) AS ?lon)
  }
